//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 22.03.2019 16:38:02
namespace DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model
{
    /// <summary>
    /// There are no comments for AlertSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("AlertSingle")]
    public partial class AlertSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Alert>
    {
        /// <summary>
        /// Initialize a new AlertSingle object.
        /// </summary>
        public AlertSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new AlertSingle object.
        /// </summary>
        public AlertSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new AlertSingle object.
        /// </summary>
        public AlertSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Alert> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for CreatedByUser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedByUser")]
        public global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.UserSingle CreatedByUser
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._CreatedByUser == null))
                {
                    this._CreatedByUser = new global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.UserSingle(this.Context, GetPath("CreatedByUser"));
                }
                return this._CreatedByUser;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.UserSingle _CreatedByUser;
    }
    /// <summary>
    /// There are no comments for Alert in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Alert")]
    public partial class Alert : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Alert object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="createdAt">Initial value of CreatedAt.</param>
        /// <param name="id_AlertType">Initial value of Id_AlertType.</param>
        /// <param name="id_AlertableObject">Initial value of Id_AlertableObject.</param>
        /// <param name="eventStartTime">Initial value of EventStartTime.</param>
        /// <param name="status">Initial value of Status.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Alert CreateAlert(int ID, 
                    global::System.DateTimeOffset createdAt, 
                    int id_AlertType, 
                    int id_AlertableObject, 
                    global::System.DateTimeOffset eventStartTime, 
                    global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.BaseAPI.CE_StatusOfAllert status)
        {
            Alert alert = new Alert();
            alert.Id = ID;
            alert.CreatedAt = createdAt;
            alert.Id_AlertType = id_AlertType;
            alert.Id_AlertableObject = id_AlertableObject;
            alert.EventStartTime = eventStartTime;
            alert.Status = status;
            return alert;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedAt")]
        public global::System.DateTimeOffset CreatedAt
        {
            get
            {
                return this._CreatedAt;
            }
            set
            {
                this.OnCreatedAtChanging(value);
                this._CreatedAt = value;
                this.OnCreatedAtChanged();
                this.OnPropertyChanged("CreatedAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTimeOffset value);
        partial void OnCreatedAtChanged();
        /// <summary>
        /// There are no comments for Property UpdatedAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UpdatedAt")]
        public global::System.Nullable<global::System.DateTimeOffset> UpdatedAt
        {
            get
            {
                return this._UpdatedAt;
            }
            set
            {
                this.OnUpdatedAtChanging(value);
                this._UpdatedAt = value;
                this.OnUpdatedAtChanged();
                this.OnPropertyChanged("UpdatedAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _UpdatedAt;
        partial void OnUpdatedAtChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnUpdatedAtChanged();
        /// <summary>
        /// There are no comments for Property Id_AlertType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id_AlertType")]
        public int Id_AlertType
        {
            get
            {
                return this._Id_AlertType;
            }
            set
            {
                this.OnId_AlertTypeChanging(value);
                this._Id_AlertType = value;
                this.OnId_AlertTypeChanged();
                this.OnPropertyChanged("Id_AlertType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id_AlertType;
        partial void OnId_AlertTypeChanging(int value);
        partial void OnId_AlertTypeChanged();
        /// <summary>
        /// There are no comments for Property Id_AlertableObject in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id_AlertableObject")]
        public int Id_AlertableObject
        {
            get
            {
                return this._Id_AlertableObject;
            }
            set
            {
                this.OnId_AlertableObjectChanging(value);
                this._Id_AlertableObject = value;
                this.OnId_AlertableObjectChanged();
                this.OnPropertyChanged("Id_AlertableObject");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id_AlertableObject;
        partial void OnId_AlertableObjectChanging(int value);
        partial void OnId_AlertableObjectChanged();
        /// <summary>
        /// There are no comments for Property AlertableObjectType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AlertableObjectType")]
        public string AlertableObjectType
        {
            get
            {
                return this._AlertableObjectType;
            }
            set
            {
                this.OnAlertableObjectTypeChanging(value);
                this._AlertableObjectType = value;
                this.OnAlertableObjectTypeChanged();
                this.OnPropertyChanged("AlertableObjectType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _AlertableObjectType;
        partial void OnAlertableObjectTypeChanging(string value);
        partial void OnAlertableObjectTypeChanged();
        /// <summary>
        /// There are no comments for Property EventStartTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("EventStartTime")]
        public global::System.DateTimeOffset EventStartTime
        {
            get
            {
                return this._EventStartTime;
            }
            set
            {
                this.OnEventStartTimeChanging(value);
                this._EventStartTime = value;
                this.OnEventStartTimeChanged();
                this.OnPropertyChanged("EventStartTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _EventStartTime;
        partial void OnEventStartTimeChanging(global::System.DateTimeOffset value);
        partial void OnEventStartTimeChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Status")]
        public global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.BaseAPI.CE_StatusOfAllert Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.BaseAPI.CE_StatusOfAllert _Status;
        partial void OnStatusChanging(global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.BaseAPI.CE_StatusOfAllert value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Id_ResponsiblePerson in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id_ResponsiblePerson")]
        public global::System.Nullable<int> Id_ResponsiblePerson
        {
            get
            {
                return this._Id_ResponsiblePerson;
            }
            set
            {
                this.OnId_ResponsiblePersonChanging(value);
                this._Id_ResponsiblePerson = value;
                this.OnId_ResponsiblePersonChanged();
                this.OnPropertyChanged("Id_ResponsiblePerson");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _Id_ResponsiblePerson;
        partial void OnId_ResponsiblePersonChanging(global::System.Nullable<int> value);
        partial void OnId_ResponsiblePersonChanged();
        /// <summary>
        /// There are no comments for Property Id_CreatedByUser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id_CreatedByUser")]
        public global::System.Nullable<int> Id_CreatedByUser
        {
            get
            {
                return this._Id_CreatedByUser;
            }
            set
            {
                this.OnId_CreatedByUserChanging(value);
                this._Id_CreatedByUser = value;
                this.OnId_CreatedByUserChanged();
                this.OnPropertyChanged("Id_CreatedByUser");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _Id_CreatedByUser;
        partial void OnId_CreatedByUserChanging(global::System.Nullable<int> value);
        partial void OnId_CreatedByUserChanged();
        /// <summary>
        /// There are no comments for Property EventStopTime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("EventStopTime")]
        public global::System.Nullable<global::System.DateTimeOffset> EventStopTime
        {
            get
            {
                return this._EventStopTime;
            }
            set
            {
                this.OnEventStopTimeChanging(value);
                this._EventStopTime = value;
                this.OnEventStopTimeChanged();
                this.OnPropertyChanged("EventStopTime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _EventStopTime;
        partial void OnEventStopTimeChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnEventStopTimeChanged();
        /// <summary>
        /// There are no comments for Property AlertClosedAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AlertClosedAt")]
        public global::System.Nullable<global::System.DateTimeOffset> AlertClosedAt
        {
            get
            {
                return this._AlertClosedAt;
            }
            set
            {
                this.OnAlertClosedAtChanging(value);
                this._AlertClosedAt = value;
                this.OnAlertClosedAtChanged();
                this.OnPropertyChanged("AlertClosedAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _AlertClosedAt;
        partial void OnAlertClosedAtChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnAlertClosedAtChanged();
        /// <summary>
        /// There are no comments for Property Id_AutomaticAlert in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id_AutomaticAlert")]
        public global::System.Nullable<int> Id_AutomaticAlert
        {
            get
            {
                return this._Id_AutomaticAlert;
            }
            set
            {
                this.OnId_AutomaticAlertChanging(value);
                this._Id_AutomaticAlert = value;
                this.OnId_AutomaticAlertChanged();
                this.OnPropertyChanged("Id_AutomaticAlert");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _Id_AutomaticAlert;
        partial void OnId_AutomaticAlertChanging(global::System.Nullable<int> value);
        partial void OnId_AutomaticAlertChanged();
        /// <summary>
        /// There are no comments for Property CreatedByUser in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedByUser")]
        public global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.User CreatedByUser
        {
            get
            {
                return this._CreatedByUser;
            }
            set
            {
                this.OnCreatedByUserChanging(value);
                this._CreatedByUser = value;
                this.OnCreatedByUserChanged();
                this.OnPropertyChanged("CreatedByUser");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.User _CreatedByUser;
        partial void OnCreatedByUserChanging(global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.User value);
        partial void OnCreatedByUserChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for UserSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("UserSingle")]
    public partial class UserSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<User>
    {
        /// <summary>
        /// Initialize a new UserSingle object.
        /// </summary>
        public UserSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new UserSingle object.
        /// </summary>
        public UserSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new UserSingle object.
        /// </summary>
        public UserSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<User> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("User")]
    public partial class User : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="createdAt">Initial value of CreatedAt.</param>
        /// <param name="isDispatcher">Initial value of IsDispatcher.</param>
        /// <param name="isDriver">Initial value of IsDriver.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static User CreateUser(int ID, global::System.DateTimeOffset createdAt, bool isDispatcher, bool isDriver)
        {
            User user = new User();
            user.Id = ID;
            user.CreatedAt = createdAt;
            user.IsDispatcher = isDispatcher;
            user.IsDriver = isDriver;
            return user;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Id_External in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id_External")]
        public string Id_External
        {
            get
            {
                return this._Id_External;
            }
            set
            {
                this.OnId_ExternalChanging(value);
                this._Id_External = value;
                this.OnId_ExternalChanged();
                this.OnPropertyChanged("Id_External");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Id_External;
        partial void OnId_ExternalChanging(string value);
        partial void OnId_ExternalChanged();
        /// <summary>
        /// There are no comments for Property CreatedAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedAt")]
        public global::System.DateTimeOffset CreatedAt
        {
            get
            {
                return this._CreatedAt;
            }
            set
            {
                this.OnCreatedAtChanging(value);
                this._CreatedAt = value;
                this.OnCreatedAtChanged();
                this.OnPropertyChanged("CreatedAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTimeOffset value);
        partial void OnCreatedAtChanged();
        /// <summary>
        /// There are no comments for Property UpdatedAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UpdatedAt")]
        public global::System.Nullable<global::System.DateTimeOffset> UpdatedAt
        {
            get
            {
                return this._UpdatedAt;
            }
            set
            {
                this.OnUpdatedAtChanging(value);
                this._UpdatedAt = value;
                this.OnUpdatedAtChanged();
                this.OnPropertyChanged("UpdatedAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _UpdatedAt;
        partial void OnUpdatedAtChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnUpdatedAtChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UserName")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
                this.OnPropertyChanged("UserName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Email")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Password")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
                this.OnPropertyChanged("Password");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property MobilePhone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MobilePhone")]
        public string MobilePhone
        {
            get
            {
                return this._MobilePhone;
            }
            set
            {
                this.OnMobilePhoneChanging(value);
                this._MobilePhone = value;
                this.OnMobilePhoneChanged();
                this.OnPropertyChanged("MobilePhone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _MobilePhone;
        partial void OnMobilePhoneChanging(string value);
        partial void OnMobilePhoneChanged();
        /// <summary>
        /// There are no comments for Property Position in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Position")]
        public string Position
        {
            get
            {
                return this._Position;
            }
            set
            {
                this.OnPositionChanging(value);
                this._Position = value;
                this.OnPositionChanged();
                this.OnPropertyChanged("Position");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Position;
        partial void OnPositionChanging(string value);
        partial void OnPositionChanged();
        /// <summary>
        /// There are no comments for Property Language in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Language")]
        public string Language
        {
            get
            {
                return this._Language;
            }
            set
            {
                this.OnLanguageChanging(value);
                this._Language = value;
                this.OnLanguageChanged();
                this.OnPropertyChanged("Language");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Language;
        partial void OnLanguageChanging(string value);
        partial void OnLanguageChanged();
        /// <summary>
        /// There are no comments for Property TimeZone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TimeZone")]
        public string TimeZone
        {
            get
            {
                return this._TimeZone;
            }
            set
            {
                this.OnTimeZoneChanging(value);
                this._TimeZone = value;
                this.OnTimeZoneChanged();
                this.OnPropertyChanged("TimeZone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _TimeZone;
        partial void OnTimeZoneChanging(string value);
        partial void OnTimeZoneChanged();
        /// <summary>
        /// There are no comments for Property YieldUnits in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("YieldUnits")]
        public string YieldUnits
        {
            get
            {
                return this._YieldUnits;
            }
            set
            {
                this.OnYieldUnitsChanging(value);
                this._YieldUnits = value;
                this.OnYieldUnitsChanged();
                this.OnPropertyChanged("YieldUnits");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _YieldUnits;
        partial void OnYieldUnitsChanging(string value);
        partial void OnYieldUnitsChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Status")]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property IsDispatcher in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IsDispatcher")]
        public bool IsDispatcher
        {
            get
            {
                return this._IsDispatcher;
            }
            set
            {
                this.OnIsDispatcherChanging(value);
                this._IsDispatcher = value;
                this.OnIsDispatcherChanged();
                this.OnPropertyChanged("IsDispatcher");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private bool _IsDispatcher;
        partial void OnIsDispatcherChanging(bool value);
        partial void OnIsDispatcherChanged();
        /// <summary>
        /// There are no comments for Property IsDriver in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IsDriver")]
        public bool IsDriver
        {
            get
            {
                return this._IsDriver;
            }
            set
            {
                this.OnIsDriverChanging(value);
                this._IsDriver = value;
                this.OnIsDriverChanged();
                this.OnPropertyChanged("IsDriver");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private bool _IsDriver;
        partial void OnIsDriverChanging(bool value);
        partial void OnIsDriverChanged();
        /// <summary>
        /// There are no comments for Property Rfid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Rfid")]
        public string Rfid
        {
            get
            {
                return this._Rfid;
            }
            set
            {
                this.OnRfidChanging(value);
                this._Rfid = value;
                this.OnRfidChanged();
                this.OnPropertyChanged("Rfid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Rfid;
        partial void OnRfidChanging(string value);
        partial void OnRfidChanged();
        /// <summary>
        /// There are no comments for Property AdditionalInfo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AdditionalInfo")]
        public string AdditionalInfo
        {
            get
            {
                return this._AdditionalInfo;
            }
            set
            {
                this.OnAdditionalInfoChanging(value);
                this._AdditionalInfo = value;
                this.OnAdditionalInfoChanged();
                this.OnPropertyChanged("AdditionalInfo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _AdditionalInfo;
        partial void OnAdditionalInfoChanging(string value);
        partial void OnAdditionalInfoChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property CropioLastSignInAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CropioLastSignInAt")]
        public global::System.Nullable<global::System.DateTimeOffset> CropioLastSignInAt
        {
            get
            {
                return this._CropioLastSignInAt;
            }
            set
            {
                this.OnCropioLastSignInAtChanging(value);
                this._CropioLastSignInAt = value;
                this.OnCropioLastSignInAtChanged();
                this.OnPropertyChanged("CropioLastSignInAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _CropioLastSignInAt;
        partial void OnCropioLastSignInAtChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCropioLastSignInAtChanged();
        /// <summary>
        /// There are no comments for Property CropioCurrentSignInAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CropioCurrentSignInAt")]
        public global::System.Nullable<global::System.DateTimeOffset> CropioCurrentSignInAt
        {
            get
            {
                return this._CropioCurrentSignInAt;
            }
            set
            {
                this.OnCropioCurrentSignInAtChanging(value);
                this._CropioCurrentSignInAt = value;
                this.OnCropioCurrentSignInAtChanged();
                this.OnPropertyChanged("CropioCurrentSignInAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _CropioCurrentSignInAt;
        partial void OnCropioCurrentSignInAtChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCropioCurrentSignInAtChanged();
        /// <summary>
        /// There are no comments for Property AuthMethod in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AuthMethod")]
        public string AuthMethod
        {
            get
            {
                return this._AuthMethod;
            }
            set
            {
                this.OnAuthMethodChanging(value);
                this._AuthMethod = value;
                this.OnAuthMethodChanged();
                this.OnPropertyChanged("AuthMethod");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _AuthMethod;
        partial void OnAuthMethodChanging(string value);
        partial void OnAuthMethodChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.Alert as global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.AlertSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.AlertSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.Alert> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.AlertSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.Alert as global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.AlertSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.AlertSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.Alert> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.AlertSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.User as global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.UserSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.UserSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.User> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.UserSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.User as global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.UserSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.UserSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.User> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.UserSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.BaseAPI
{
    /// <summary>
    /// There are no comments for CE_StatusOfAllert in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CE_StatusOfAllert")]
    public enum CE_StatusOfAllert
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Closed")]
        Closed = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Open")]
        Open = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Notification")]
        Notification = 2
    }
}
namespace DatEx.Cropio.Proxy.ODataApi.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "DatEx.Cropio.Proxy.Model", "DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "DatEx.Cropio.BaseAPI", "DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.BaseAPI");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "DatEx.Cropio.Proxy.ODataApi.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("DatEx.Cropio.Proxy.Model.", originalNameAttribute.OriginalName);
                }
                return string.Concat("DatEx.Cropio.Proxy.Model.", clientType.Name);
            }
            if (clientType.Namespace.Equals("DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.BaseAPI", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("DatEx.Cropio.BaseAPI.", originalNameAttribute.OriginalName);
                }
                return string.Concat("DatEx.Cropio.BaseAPI.", clientType.Name);
            }
            if (clientType.Namespace.Equals("DatEx.Cropio.Proxy.ODataApi.Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Alerts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Alerts")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.Alert> Alerts
        {
            get
            {
                if ((this._Alerts == null))
                {
                    this._Alerts = base.CreateQuery<global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.Alert>("Alerts");
                }
                return this._Alerts;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.Alert> _Alerts;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Users")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.User> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.User>("Users");
                }
                return this._Users;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.User> _Users;
        /// <summary>
        /// There are no comments for Alerts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToAlerts(global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.Alert alert)
        {
            base.AddObject("Alerts", alert);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToUsers(global::DatEx.Cropio.Proxy.ODataApi.DatEx.Cropio.Proxy.Model.User user)
        {
            base.AddObject("Users", user);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""DatEx.Cropio.Proxy.Model"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Alert"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""CreatedAt"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""UpdatedAt"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""Id_AlertType"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Id_AlertableObject"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""AlertableObjectType"" Type=""Edm.String"" />
        <Property Name=""EventStartTime"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""Status"" Type=""DatEx.Cropio.BaseAPI.CE_StatusOfAllert"" Nullable=""false"" />
        <Property Name=""Description"" Type=""Edm.String"" />
        <Property Name=""Id_ResponsiblePerson"" Type=""Edm.Int32"" />
        <Property Name=""Id_CreatedByUser"" Type=""Edm.Int32"" />
        <Property Name=""EventStopTime"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""AlertClosedAt"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""Id_AutomaticAlert"" Type=""Edm.Int32"" />
        <NavigationProperty Name=""CreatedByUser"" Type=""DatEx.Cropio.Proxy.Model.User"" />
      </EntityType>
      <EntityType Name=""User"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Id_External"" Type=""Edm.String"" />
        <Property Name=""CreatedAt"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""UpdatedAt"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""UserName"" Type=""Edm.String"" />
        <Property Name=""Email"" Type=""Edm.String"" />
        <Property Name=""Password"" Type=""Edm.String"" />
        <Property Name=""MobilePhone"" Type=""Edm.String"" />
        <Property Name=""Position"" Type=""Edm.String"" />
        <Property Name=""Language"" Type=""Edm.String"" />
        <Property Name=""TimeZone"" Type=""Edm.String"" />
        <Property Name=""YieldUnits"" Type=""Edm.String"" />
        <Property Name=""Status"" Type=""Edm.String"" />
        <Property Name=""IsDispatcher"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""IsDriver"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""Rfid"" Type=""Edm.String"" />
        <Property Name=""AdditionalInfo"" Type=""Edm.String"" />
        <Property Name=""Description"" Type=""Edm.String"" />
        <Property Name=""CropioLastSignInAt"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""CropioCurrentSignInAt"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""AuthMethod"" Type=""Edm.String"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""DatEx.Cropio.BaseAPI"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EnumType Name=""CE_StatusOfAllert"">
        <Member Name=""Closed"" Value=""0"" />
        <Member Name=""Open"" Value=""1"" />
        <Member Name=""Notification"" Value=""2"" />
      </EnumType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Alerts"" EntityType=""DatEx.Cropio.Proxy.Model.Alert"">
          <NavigationPropertyBinding Path=""CreatedByUser"" Target=""Users"" />
        </EntitySet>
        <EntitySet Name=""Users"" EntityType=""DatEx.Cropio.Proxy.Model.User"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.CsdlReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
